from django.urls import path

from infermerieapp.views import *

urlpatterns = [
    path('', index, name='index'),
    path('login/',auth_login),
    path('logout/',auth_logout),
    path('dashbord/',gestionnaire),
    path('filtre/', filter_employers),
    path('pris_charge/', pris_en_charge, name='pris_en_charge'),
    path('referencer/pris_en_charge', referencer_pris_en_charge, name='referencer'),
    path('referencer/supprimer', supprimer, name='supprimer'),
    path('ordonnance/', ordonnance_view, name='ordonnance'),
    path('ordonnance/generate/', ordonnance_generate, name='ordonnance_generate'),
    path('liste_ordonnances/', liste_ordonnances, name='liste_ordonnances'),
    path('ordonnances/<int:pk>/', ordonnance_modifier, name='ordonnances'),
    path('ordonnance/pdf/<int:pk>/', voire_ordonnance, name='ordonnance_terminer'),
    path('liste_ordonnances/chef/', chef, name='liste_ordonnances'),
    path('liste_ordonnances/medecin/', medecin, name='liste_ordonnances_medecin'),
    path('tableau_referencer/' , tableau_referencer),
    path('institution/', institution_view, name='institution'),
    path('institution/ajouter/', institution_ajouter, name='institution_ajouter'),
    path('institution/supprimer/<int:pk>/', institution_supprimer, name='institution_supprimer'),
    path('consultation/', consultation_view, name='consultation'),
    path('consultation/ajouter/', consultation_ajouter, name='consultation_ajouter'),
    path('consultation/supprimer/<int:pk>/', consultation_supprimer, name='consultation_supprimer'),
    path('analyse/', analyse_view, name='analyse'),     
    path('analyse/ajouter/', analyse_ajouter, name='analyse_ajouter'),
    path('analyse/supprimer/<int:pk>/', analyse_supprimer, name='analyse_supprimer'),
    path('examen/', examen_view, name='examen'),
    path('examen/ajouter/', examen_ajouter, name='examen_ajouter'),
    path('examen/supprimer/<int:pk>/', examen_supprimer, name='examen_supprimer'),
    path('hospitalisation/', hospitalisation_view, name='hospitalisation'),
    path('hospitalisation/ajouter/', hospitalisation_ajouter, name='hospitalisation_ajouter'),
    path('hospitalisation/supprimer/<int:pk>/', hospitalisation_supprimer, name='hospitalisation_supprimer'),
    path('irm/', irm_view, name='irm'),
    path('irm/ajouter/', irm_ajouter, name='irm_ajouter'),
    path('irm/supprimer/<int:pk>/', irm_supprimer, name='irm_supprimer'),
    path('echographie/',echographie_view, name='echographie'),
    path('echographie/ajouter/', echographie_ajouter, name='echographie_ajouter'),
    path('echographie/supprimer/<int:pk>/', echographie_supprimer, name='echographie_supprimer'),
    path('radiographie/', radiographie_view, name='radiographie'),
    path('radiographie/ajouter/', radiographie_ajouter, name='radiographie_ajouter'),
    path('radiographie/supprimer/<int:pk>/', radiographie_supprimer, name='radiographie_supprimer'),
    path('hospitalisation/', hospitalisation_view, name='hospitalisation'),
    path('hospitalisation/ajouter/', hospitalisation_ajouter, name='hospitalisation_ajouter'),
    path('hospitalisation/supprimer/<int:pk>/', hospitalisation_supprimer, name='hospitalisation_supprimer'),
    path('produit/', produit_view, name='produit'),
    path('produit/ajouter/', produit_ajouter, name='produit_ajouter'),
    path('produit/supprimer/<int:pk>/', produit_supprimer, name='produit_supprimer'),
    path('scanner/', scanner_view, name='scanner'),
    path('scanner/ajouter/', scanner_ajouter, name='scanner_ajouter'),
    path('scanner/supprimer/<int:pk>/', scanner_supprimer, name='scanner_supprimer'),
    path('ajouter/', ajouter, name='ajouter'),
    path('liste_bon/', liste_bon, name='liste_bon'),
    path('ajouter_pris/', ajouter_pris, name='ajouter_pris'),
    path('generate_pris/', generate_pris, name='generate_pris'),
    path('liste_pris_en_charges/chef/',chef_pris_en_charge),
    path('liste_pris_en_charge/', liste_pris_en_charges),
    path('liste_pris_en_charges/chef/', pris_en_charge_chef, name='liste_pris_en_charges'),
    path('pris_en_charge/pdf/<int:pk>/', voire_pris_en_charge),
    path('technicien/',technicien),
    path('liste_pris_en_charges/medecin/',medecin_pris_en_charge)
]