# Generated by Django 5.2.4 on 2025-08-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prisencharge',
            name='analyse',
        ),
        migrations.RemoveField(
            model_name='prisencharge',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='prisencharge',
            name='examen',
        ),
        migrations.AddField(
            model_name='prisencharge',
            name='analyses',
            field=models.ManyToManyField(blank=True, related_name='analyses', to='infermerieapp.analyse'),
        ),
        migrations.AddField(
            model_name='prisencharge',
            name='consultations',
            field=models.ManyToManyField(blank=True, related_name='consultations', to='infermerieapp.consultation'),
        ),
        migrations.AddField(
            model_name='prisencharge',
            name='echographies',
            field=models.ManyToManyField(blank=True, related_name='echographies', to='infermerieapp.echographie'),
        ),
        migrations.AddField(
            model_name='prisencharge',
            name='examens',
            field=models.ManyToManyField(blank=True, related_name='examens', to='infermerieapp.examen'),
        ),
        migrations.AddField(
            model_name='prisencharge',
            name='hospitalisations',
            field=models.ManyToManyField(blank=True, related_name='hospitalisations', to='infermerieapp.hospitalisation'),
        ),
        migrations.AddField(
            model_name='prisencharge',
            name='irms',
            field=models.ManyToManyField(blank=True, related_name='irms', to='infermerieapp.irm'),
        ),
        migrations.AddField(
            model_name='prisencharge',
            name='produits',
            field=models.ManyToManyField(blank=True, related_name='produits', to='infermerieapp.produit'),
        ),
        migrations.AddField(
            model_name='prisencharge',
            name='radiographies',
            field=models.ManyToManyField(blank=True, related_name='radiographies', to='infermerieapp.radiographie'),
        ),
        migrations.AddField(
            model_name='prisencharge',
            name='scanners',
            field=models.ManyToManyField(blank=True, related_name='scanners', to='infermerieapp.scanner'),
        ),
        migrations.AddField(
            model_name='prisencharge',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('validée', 'Validée'), ('annulée', 'Annulée'), ('terminée', 'Terminée')], default='en attente', max_length=20),
        ),
    ]
