# Generated by Django 5.2.4 on 2025-07-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='matricule',
            field=models.CharField(max_length=7),
        ),
    ]
