# Generated by Django 5.2.4 on 2025-08-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='nom_medecin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='nom_technicien',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
