# Generated by Django 5.2.4 on 2025-08-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0002_ordonnance_nom_medecin_ordonnance_nom_technicien'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='nom_chef',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
