# Generated by Django 5.2.4 on 2025-08-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0002_remove_prisencharge_analyse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prisencharge',
            old_name='gfu_whatsap',
            new_name='gfu',
        ),
        migrations.AddField(
            model_name='prisencharge',
            name='whatsap',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
