# Generated by Django 5.2.4 on 2025-07-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0002_alter_employer_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='matricule',
            field=models.CharField(max_length=100),
        ),
    ]
