# Generated by Django 5.2.4 on 2025-07-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0003_alter_employer_matricule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='Inam',
            new_name='inam',
        ),
    ]
