# Generated by Django 5.2.4 on 2025-08-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0003_rename_gfu_whatsap_prisencharge_gfu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisencharge',
            name='nom_chef',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prisencharge',
            name='nom_medecin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prisencharge',
            name='nom_technicien',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
