# Generated by Django 5.2.4 on 2025-08-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0003_ordonnance_nom_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='validate_chef',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='validate_medecin',
            field=models.BooleanField(default=False),
        ),
    ]
