# Generated by Django 5.2.4 on 2025-08-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0004_ordonnance_validate_chef_ordonnance_validate_medecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='ur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='dosage',
            field=models.CharField(blank=True, choices=[('cp', 'CP'), ('sirop', 'SIROP'), ('gel', 'GEL'), ('sachet', 'SACHET'), ('creme', 'CREME'), ('injectable', 'INJECTABLE')], max_length=50, null=True),
        ),
    ]
