# Generated by Django 5.2.4 on 2025-08-24 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0004_prisencharge_nom_chef_prisencharge_nom_medecin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisencharge',
            name='consultations',
            field=models.ManyToManyField(blank=True, related_name='pris_en_charges', to='infermerieapp.consultation'),
        ),
        migrations.CreateModel(
            name='PrisEnChargeActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acte_type', models.CharField(max_length=50)),
                ('acte_id', models.PositiveIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pris_en_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actes', to='infermerieapp.prisencharge')),
            ],
        ),
    ]
