# Generated by Django 5.2.4 on 2025-08-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0005_remove_ordonnance_heure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='medecin',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('validée', 'Validée'), ('annulée', 'Annulée')], default='en attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
