# Generated by Django 5.2.4 on 2025-08-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0005_employer_ur_medicament_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='gfu_whatsap',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
