# Generated by Django 5.2.4 on 2025-08-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0006_ordonnance_gfu_whatsap'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='prescription',
            field=models.CharField(blank=True, choices=[('Normale', 'Normale'), ('Urgent', 'Urgent'), ('Chronique', 'Chronique')], max_length=20, null=True),
        ),
    ]
