# Generated by Django 5.2.4 on 2025-08-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0006_remove_ordonnance_medecin_ordonnance_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('validée', 'Validée'), ('annulée', 'Annulée'), ('terminée', 'Terminée')], default='en attente', max_length=20),
        ),
    ]
