# Generated by Django 5.2.4 on 2025-08-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0008_ordonnance_duree_ordonnance_type_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='type_duree',
        ),
        migrations.AddField(
            model_name='medicament',
            name='duree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='type_duree',
            field=models.CharField(blank=True, choices=[('jour', 'Jour'), ('semaine', 'Semaine'), ('mois', 'Mois')], max_length=20, null=True),
        ),
    ]
