# Generated by Django 5.2.4 on 2025-08-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infermerieapp', '0009_remove_ordonnance_duree_remove_ordonnance_type_duree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='diagnostic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
